apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: nb-artifactory-cleanup

#spec section required. 
spec:
  schedule: "0 3 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nb-artifactory-cleanup
              image: myimagenamehere
              command: ["run-job.sh"] # this would override whats in the Dockerfile
              args: ["${{ secrets.ARTI_USERNAME }}","${{ secrets.ARTI_PWRD }}","lol"] #things like username, password, actual run "DELETE" here some secrets things
          restartPolicy: OnFailure

# apply with kubectl apply -f basic-cron.yaml