apiVersion: batch/v1
kind: CronJob
metadata:
  name: image-cleanup
  namespace: notebook-cleanup
spec:
  schedule: "0 22 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: notebook-img-cleanup-sa
          automountServiceAccountToken: true
          restartPolicy: OnFailure
          containers:
          - name: hello
            image: dockerimagehere
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            env:
              - name: JFROG_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: jfrog-secret
                    key: username
              - name: JFROG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jfrog-secret
                    key: password
# UNFINISHED, must create secret in namespace for this
