namespace: monitoring


# Every month day 1
schedule: "0 0 1 * *"

image:
  registry: registry
  name: NAME-OF-IMAGE
  version: "1.9"

  imagePullSecrets: []
  #- name: image-pull-secret

# If you run the script interactively,
# is this needed for this use-case?
elasticsearch:
  host: http://elastic
  index: 'kubeflow-pipeline-secrets'

secretscan:
  max_entropy: "3.5"